{% set name = "kurl" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kurl-{{ version }}.tar.gz
  sha256: 1b1ff745e8dd5c04baab33027205c7fa0f9adcfdd971b7925a649c8069fbcf01

build:
  entry_points:
    - kurl = kurl.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - kurl
  commands:
    - pip check
    - kurl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/kurl
  summary: A library to fetch resources with an implementation of conditional request and a smart responses caching system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
